### ISSUE TITLE
Reload homepage brings error message

### ISSUE THREAD

**Issue by HonkXL** [JustCarmen/webtrees-fancy-imagebar#67]
I set "show on homepage only". When I load the homepage using the house-icon and the tree name, everything is ok - startpage is displayed with fancy imagebar. When I now click the icon again and select the same tree again, I get this error message:

imagecopyresampled() expects parameter 2 to be resource, bool given …/modules_v4/jc-fancy-imagebar/FancyImagebarModule.php:533
#0 …/modules_v4/jc-fancy-imagebar/FancyImagebarModule.php(533): imagecopyresampled()
#1 …/modules_v4/jc-fancy-imagebar/FancyImagebarModule.php(345): JustCarmen\Webtrees\Module\FancyImagebarModule->fancyThumb()
#2 …/modules_v4/jc-fancy-imagebar/FancyImagebarModule.php(220): JustCarmen\Webtrees\Module\FancyImagebarModule->fancyImagebar()
#3 …/resources/views/layouts/default.phtml(190): JustCarmen\Webtrees\Module\FancyImagebarModule->bodyContent()
#4 [internal function]: Fisharebest\Webtrees\View::{closure}()
#5 …/vendor/illuminate/support/Collection.php(1120): array_map()
#6 …/resources/views/layouts/default.phtml(191): Illuminate\Support\Collection->map()
#7 …/app/View.php(189): include('/home/genealogi...')
#8 …/app/View.php(286): Fisharebest\Webtrees\View->render()
#9 …/app/Helpers/functions.php(203): Fisharebest\Webtrees\View::make()
#10 …/app/Http/ViewResponseTrait.php(55): view()
#11 …/app/Http/RequestHandlers/TreePage.php(93): Fisharebest\Webtrees\Http\RequestHandlers\TreePage->viewResponse()
#12 …/app/Http/Middleware/WrapHandler.php(83): Fisharebest\Webtrees\Http\RequestHandlers\TreePage->handle()
#13 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\WrapHandler->process()
#14 …/modules_v4/vesta_classic_look_and_feel/ClassicLAFModule.php(168): Middleland\Dispatcher->handle()
#15 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Cissee\Webtrees\Module\ClassicLAF\ClassicLAFModule->process()
#16 …/modules_v4/reminder/src/Modules/ReminderModule.php(98): Middleland\Dispatcher->handle()
#17 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): UksusoFF\WebtreesModules\Reminder\Modules\ReminderModule->process()
#18 …/app/Module/HitCountFooterModule.php(157): Middleland\Dispatcher->handle()
#19 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\HitCountFooterModule->process()
#20 …/app/Http/Middleware/CheckCsrf.php(75): Middleland\Dispatcher->handle()
#21 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process()
#22 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
#23 …/app/Http/Middleware/Router.php(166): Middleland\Dispatcher->dispatch()
#24 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router->process()
#25 …/app/Http/Middleware/BootModules.php(62): Middleland\Dispatcher->handle()
#26 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process()
#27 …/app/Http/Middleware/LoadRoutes.php(76): Middleland\Dispatcher->handle()
#28 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes->process()
#29 …/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher->handle()
#30 …/vendor/illuminate/database/Concerns/ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}()
#31 …/app/Http/Middleware/UseTransaction.php(46): Illuminate\Database\Connection->transaction()
#32 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process()
#33 …/app/Http/Middleware/DoHousekeeping.php(74): Middleland\Dispatcher->handle()
#34 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process()
#35 …/app/Http/Middleware/UseTheme.php(70): Middleland\Dispatcher->handle()
#36 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme->process()
#37 …/app/Http/Middleware/CheckForMaintenanceMode.php(51): Middleland\Dispatcher->handle()
#38 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->process()
#39 …/app/Http/Middleware/UseLanguage.php(70): Middleland\Dispatcher->handle()
#40 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage->process()
#41 …/app/Http/Middleware/UseSession.php(71): Middleland\Dispatcher->handle()
#42 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process()
#43 …/app/Http/Middleware/UpdateDatabaseSchema.php(58): Middleland\Dispatcher->handle()
#44 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process()
#45 …/app/Http/Middleware/UseDebugbar.php(67): Middleland\Dispatcher->handle()
#46 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDebugbar->process()
#47 …/app/Http/Middleware/UseDatabase.php(117): Middleland\Dispatcher->handle()
#48 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process()
#49 …/app/Http/Middleware/BadBotBlocker.php(217): Middleland\Dispatcher->handle()
#50 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process()
#51 …/app/Http/Middleware/CompressResponse.php(75): Middleland\Dispatcher->handle()
#52 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse->process()
#53 …/app/Http/Middleware/RegisterFactories.php(74): Middleland\Dispatcher->handle()
#54 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RegisterFactories->process()
#55 …/vendor/middlewares/client-ip/src/ClientIp.php(81): Middleland\Dispatcher->handle()
#56 …/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process()
#57 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process()
#58 …/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher->handle()
#59 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process()
#60 …/app/Http/Middleware/BaseUrl.php(77): Middleland\Dispatcher->handle()
#61 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process()
#62 …/app/Http/Middleware/ReadConfigIni.php(69): Middleland\Dispatcher->handle()
#63 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process()
#64 …/app/Http/Middleware/SecurityHeaders.php(47): Middleland\Dispatcher->handle()
#65 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process()
#66 …/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle()
#67 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process()
#68 …/app/Http/Middleware/PhpEnvironment.php(49): Middleland\Dispatcher->handle()
#69 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\PhpEnvironment->process()
#70 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
#71 …/index.php(57): Middleland\Dispatcher->dispatch()
#72 {main}

**Comment by JustCarmen** [comment]
I cannot reproduce this. I suspect a corrupt image. If you refresh the page again do you still see the error message?

**Comment by HonkXL** [comment]
I tried it again with a test-tree - there I can not reproduce it. Seems really to be a problem with one of the media files in my master tree. Think you can close this issue.
